apiVersion: v1
kind: Service
metadata:
  name: foreend-platform
  labels:
    app: foreend-platform
spec:
  type: ClusterIP
  selector:
    app: foreend-platform
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
